### ISSUE TITLE
VS update

### ISSUE THREAD

**Issue by Nantiee** [dqsully/octobercms-template-language#1]
Hi,

I use your nice plugin since a few weeks, but it's not working anymore since this week Visual Studio Code update.

![image](https://user-images.githubusercontent.com/2286536/36074666-b590959c-0f43-11e8-9b8a-114e5d1fd5af.png)

Thanls,

Anne :)

**Comment by dqsully** [comment]
Thanks for bringing this up. I don't use VS Code so I never would have noticed this. It looks like Microsoft changed the grammar rules a little bit again and now my package loops indefinitely. If everything goes right I should be able to push out a fix today.

**Comment by dqsully** [comment]
Just pushed a fix to the VS Code Extension Marketplace. Please update the package on your computer and test it out, and if everything is good we can close this issue.

**Comment by Nantiee** [comment]
It's working, many thanks ! :)
