### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by martin-badin** [dqsully/octobercms-template-language#3]
Please, add support for html formatter. Thanks

**Comment by dqsully** [comment]
At the moment I don't feel like writing this, it's just too much work. There are also problems with using a vanilla HTML formatter for twig (see https://stackoverflow.com/questions/31631549/how-to-setup-atom-beautify-with-twig-files). If someone wants to write this feature, by all means, have at it.

**Comment by dqsully** [comment]
Looking back at this, it appears someone actually built a Twig beautifier into `prettydiff`. Maybe `prettydiff` could be integrated into this package or maybe Twig and OctoberCMS can by built into `js-beautify`. I still don't really have time for this, but if someone wants to look into it here are some relevant links:

https://github.com/HookyQR/VSCodeBeautify/issues/163  
https://github.com/mblode/vscode-twig-language/blob/master/src/extension.js  
https://github.com/beautify-web/js-beautify/issues/991
