### ISSUE TITLE
Quotation marks breaks syntax highlighting

### ISSUE THREAD

**Issue by damsfx** [dqsully/octobercms-template-language#4]
Quotes and single quote in HTML section breaks the syntax highlighting if they are not paired !

Try : 
````
<div class="foo">
    <div class="bar">
        <p>due to this ' ,this line breaks the syntax highlighting</p>
        <p>This line too because of this " not paired quotation mark</p>
    </div>
</div>
````
No HighLight needed if those quotation marks are presents bettween > and < tags.

**Comment by dqsully** [comment]
Did you put `{##}` at the beginning of your twig/html section? If it's not there, then VS Code thinks that your html is actually INI or PHP code.

**Comment by damsfx** [comment]
Shame on me!  
I missed that info in the readme.  :-/

> Because of the limitations of the VS Code grammar system, `{##}` must be at the beginning of your Twig/HTML script.

Too bad I have to do this... I'll forget it every time.

**Comment by dqsully** [comment]
Yeah, I'm sorry, I couldn't make it work otherwise. Maybe when/if VS Code adopts tree-sitter highlighting I could make it work finally.
