### ISSUE TITLE
template colors not working for .htm

### ISSUE THREAD

**Issue by elbojoloco** [dqsully/octobercms-template-language#5]
Hey, after installing the extension in vscode and reloading, my .htm file does not look like the example.

I added `;;` at line 1 and `{##}` before my twig/html part:

![image](https://user-images.githubusercontent.com/7912315/52479061-a805dc80-2ba7-11e9-8c68-a188f4010f3e.png)

What am i doing wrong?

**Comment by AlexisWalravens** [comment]
Try removing your php tags in the php part of the file.

**Comment by elbojoloco** [comment]
That fixed it. however when I edit the template in the CMS part of the back-end, it adds the `php` tags again, how to disable that behavior?

**Comment by dqsully** [comment]
I'll see if I can add some functionality in my package to solve that case.

**Comment by dqsully** [comment]
Alright, I just pushed an update to my package that should fix this case
